name: release beta

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/CHANGELOG.md"

jobs:
  release:
    name: Release Beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: |
          npx lerna bootstrap
          if [[ -n $(git status -s) ]]; then
            echo "Error: file tree is not clean"
            git status
            exit 1
          fi

      - run: git describe --abbrev=0 --tags

      - run: npx lerna updated
