# based on: https://github.com/hirosystems/gh-actions-example/blob/main/.github/workflows/ci.yml
name: release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/CHANGELOG.md"
      - "**/package.json"

jobs:
  release:
    name: Release
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: |
          npx lerna bootstrap
          if [[ -n $(git status -s) ]]; then
            echo "Error: file tree is not clean"
            git status
            exit 1
          fi

      - name: Test
        run: npm run test

      - name: Build
        run: NODE_ENV=production npm run build

      - name: "Release: Version"
        run: npx lerna version --conventional-commits --conventional-prerelease --preid beta --no-push --yes

      - name: "Release: Publish"
        run: npx lerna publish --pre-dist-tag beta --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Release: Push Tag"
        run: git push origin $(git describe --abbrev=0 --tags)
