name: release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/CHANGELOG.md"
      - "**/package.json"
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only run on non-PR events or only PRs that aren't from forks
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Bootstrap
        run: npm run bootstrap

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: "Release: Version"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          lerna version --conventional-commits --conventional-prerelease --yes

      - name: "Release: Publish"
        run: lerna publish from-git --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
