name: version

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

  workflow_dispatch:

jobs:
  pre_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  version:
    runs-on: ubuntu-latest
    needs: pre_run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run bootstrap

      # hack changesets/action to allow not using changesets
      - run: |
          npx changeset init
          npx changeset --empty
          echo '.changeset/' >> .git/info/exclude

      - run: git tag -d $(git tag | grep 'beta')

      - name: Create Release Pull Request
        uses: janniks/changesets-action@main
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
